#!/usr/bin/env python3
"""
RamAI credential helper using the Python keyring library.

Stores secrets in the OS credential store (on this machine: Windows
Credential Manager via WinVaultKeyring). Nothing sensitive is written
to the git repo.

Usage examples (from D:\\RamAI):

  # One-time: import from existing local files into Keyring
  python tools/keyring_secrets.py import-local

  # Interactive set / get / delete
  python tools/keyring_secrets.py set wifi/ssid
  python tools/keyring_secrets.py get mqtt/password
  python tools/keyring_secrets.py list
  python tools/keyring_secrets.py delete mqtt/password

  # Regenerate gitignored secrets.h files for Arduino sketches
  python tools/keyring_secrets.py write-arduino

  # Regenerate Unreal + RamMQTT local config files
  python tools/keyring_secrets.py write-configs
"""

from __future__ import annotations

import argparse
import getpass
import json
import re
import sys
from pathlib import Path

try:
    import keyring
except ImportError:
    print(
        "keyring is not installed for this Python.\n"
        "Install with:  python -m pip install keyring",
        file=sys.stderr,
    )
    sys.exit(1)

# Service name groups related RamAI secrets in Credential Manager.
SERVICE = "RamAI"

# Logical credential keys we manage.
KEYS = [
    "wifi/ssid",
    "wifi/password",
    "mqtt/host",
    "mqtt/port",
    "mqtt/username",
    "mqtt/password",
    # Optional secondary MQTT account used by KegBot distance sensor
    "mqtt/kegbot_username",
    "mqtt/kegbot_password",
]

REPO_ROOT = Path(__file__).resolve().parents[1]

ARDUINO_SKETCHES = [
    REPO_ROOT / "RainESP32",
    REPO_ROOT / "FunHouseMainTerminal",
    REPO_ROOT / "BeerAutomations" / "DistanceSensor",
    REPO_ROOT / "BeerAutomations" / "KegTemp",
]

SECRETS_H_TEMPLATE = """\
#pragma once
// LOCAL ONLY — gitignored. Generated by tools/keyring_secrets.py
// Do not commit this file.

const char* ssid = "{ssid}";
const char* password = "{wifi_password}";

const char* mqtt_server = "{mqtt_host}";
const int mqtt_port = {mqtt_port};
const char* mqtt_user = "{mqtt_user}";
const char* mqtt_pass = "{mqtt_pass}";
"""


def require(key: str) -> str:
    value = keyring.get_password(SERVICE, key)
    if value is None or value == "":
        raise SystemExit(
            f"Missing Keyring entry: service={SERVICE!r} username={key!r}\n"
            f"Set it with:  python tools/keyring_secrets.py set {key}"
        )
    return value


def optional(key: str, default: str = "") -> str:
    value = keyring.get_password(SERVICE, key)
    return default if value is None else value


def cmd_list(_: argparse.Namespace) -> None:
    print(f"Keyring backend: {keyring.get_keyring()}")
    print(f"Service: {SERVICE}")
    print()
    for key in KEYS:
        value = keyring.get_password(SERVICE, key)
        if value is None:
            status = "(not set)"
        elif key.endswith("password"):
            status = "(set, hidden)"
        else:
            status = value
        print(f"  {key:24} {status}")


def cmd_get(args: argparse.Namespace) -> None:
    value = keyring.get_password(SERVICE, args.key)
    if value is None:
        raise SystemExit(f"No value stored for {args.key!r}")
    # Avoid echoing passwords unless --show is passed
    if args.key.endswith("password") and not args.show:
        print("(set — pass --show to print)")
    else:
        print(value)


def cmd_set(args: argparse.Namespace) -> None:
    if args.value is not None:
        value = args.value
    elif args.key.endswith("password"):
        value = getpass.getpass(f"Enter value for {args.key}: ")
    else:
        value = input(f"Enter value for {args.key}: ").strip()
    if value == "":
        raise SystemExit("Empty value not stored.")
    keyring.set_password(SERVICE, args.key, value)
    print(f"Stored {SERVICE} / {args.key}")


def cmd_delete(args: argparse.Namespace) -> None:
    try:
        keyring.delete_password(SERVICE, args.key)
        print(f"Deleted {SERVICE} / {args.key}")
    except keyring.errors.PasswordDeleteError:
        raise SystemExit(f"No value stored for {args.key!r}")


def _parse_c_string(text: str, name: str) -> str | None:
    # const char* name = "value";
    m = re.search(
        rf'const\s+char\s*\*\s*{re.escape(name)}\s*=\s*"([^"]*)"',
        text,
    )
    return m.group(1) if m else None


def _parse_c_int(text: str, name: str) -> str | None:
    m = re.search(rf'const\s+int\s+{re.escape(name)}\s*=\s*(\d+)', text)
    return m.group(1) if m else None


def cmd_import_local(_: argparse.Namespace) -> None:
    """Import from existing gitignored local files into Keyring."""
    imported = 0

    # Prefer FunHouse / Rain secrets.h as primary WiFi + MQTT
    primary_paths = [
        REPO_ROOT / "FunHouseMainTerminal" / "secrets.h",
        REPO_ROOT / "RainESP32" / "secrets.h",
        REPO_ROOT / "BeerAutomations" / "KegTemp" / "secrets.h",
    ]
    primary_text = None
    for path in primary_paths:
        if path.is_file():
            primary_text = path.read_text(encoding="utf-8", errors="replace")
            print(f"Reading primary secrets from {path}")
            break

    if primary_text:
        mapping = {
            "wifi/ssid": _parse_c_string(primary_text, "ssid"),
            "wifi/password": _parse_c_string(primary_text, "password"),
            "mqtt/host": _parse_c_string(primary_text, "mqtt_server"),
            "mqtt/port": _parse_c_int(primary_text, "mqtt_port"),
            "mqtt/username": _parse_c_string(primary_text, "mqtt_user"),
            "mqtt/password": _parse_c_string(primary_text, "mqtt_pass"),
        }
        for key, value in mapping.items():
            if value is not None and value != "":
                keyring.set_password(SERVICE, key, value)
                print(f"  imported {key}")
                imported += 1

    # Distance sensor may use a different MQTT account
    kegbot = REPO_ROOT / "BeerAutomations" / "DistanceSensor" / "secrets.h"
    if kegbot.is_file():
        text = kegbot.read_text(encoding="utf-8", errors="replace")
        user = _parse_c_string(text, "mqtt_user")
        pw = _parse_c_string(text, "mqtt_pass")
        if user:
            keyring.set_password(SERVICE, "mqtt/kegbot_username", user)
            print("  imported mqtt/kegbot_username")
            imported += 1
        if pw:
            keyring.set_password(SERVICE, "mqtt/kegbot_password", pw)
            print("  imported mqtt/kegbot_password")
            imported += 1

    # Unreal / plugin JSON configs (fill any gaps)
    for json_path in [
        REPO_ROOT / "UnrealBuild" / "RamBedAI" / "Config" / "mqtt_local.json",
        REPO_ROOT / "MQTTcustomPlugin" / "config" / "local_profile.json",
    ]:
        if not json_path.is_file():
            continue
        print(f"Reading {json_path}")
        data = json.loads(json_path.read_text(encoding="utf-8"))
        # local_profile has profiles[]; mqtt_local is flat
        if "profiles" in data and data["profiles"]:
            profile = data["profiles"][0]
        else:
            profile = data
        for key, field in [
            ("mqtt/host", "host"),
            ("mqtt/port", "port"),
            ("mqtt/username", "username"),
            ("mqtt/password", "password"),
        ]:
            if keyring.get_password(SERVICE, key):
                continue
            if field in profile and str(profile[field]) != "":
                keyring.set_password(SERVICE, key, str(profile[field]))
                print(f"  imported {key} from {json_path.name}")
                imported += 1

    if imported == 0:
        print("Nothing imported. Set values manually with:")
        print("  python tools/keyring_secrets.py set wifi/ssid")
    else:
        print(f"Done. Imported {imported} entries into Windows Credential Manager.")
        print("Run:  python tools/keyring_secrets.py list")


def cmd_write_arduino(_: argparse.Namespace) -> None:
    ssid = require("wifi/ssid")
    wifi_password = require("wifi/password")
    mqtt_host = require("mqtt/host")
    mqtt_port = optional("mqtt/port", "1883")
    mqtt_user = require("mqtt/username")
    mqtt_pass = require("mqtt/password")
    keg_user = optional("mqtt/kegbot_username", mqtt_user)
    keg_pass = optional("mqtt/kegbot_password", mqtt_pass)

    for sketch in ARDUINO_SKETCHES:
        if not sketch.is_dir():
            print(f"skip missing {sketch}")
            continue
        user, pw = mqtt_user, mqtt_pass
        if sketch.name == "DistanceSensor":
            user, pw = keg_user, keg_pass
        content = SECRETS_H_TEMPLATE.format(
            ssid=ssid,
            wifi_password=wifi_password,
            mqtt_host=mqtt_host,
            mqtt_port=mqtt_port,
            mqtt_user=user,
            mqtt_pass=pw,
        )
        out = sketch / "secrets.h"
        out.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {out}")


def cmd_write_configs(_: argparse.Namespace) -> None:
    host = require("mqtt/host")
    port = int(optional("mqtt/port", "1883"))
    username = require("mqtt/username")
    password = require("mqtt/password")

    unreal = {
        "host": host,
        "port": port,
        "client_id": "RamBedAI",
        "username": username,
        "password": password,
    }
    unreal_path = REPO_ROOT / "UnrealBuild" / "RamBedAI" / "Config" / "mqtt_local.json"
    unreal_path.parent.mkdir(parents=True, exist_ok=True)
    unreal_path.write_text(json.dumps(unreal, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {unreal_path}")

    # Prefer updating local_profile from default_profile if present
    default_path = REPO_ROOT / "MQTTcustomPlugin" / "config" / "default_profile.json"
    local_path = REPO_ROOT / "MQTTcustomPlugin" / "config" / "local_profile.json"
    if default_path.is_file():
        data = json.loads(default_path.read_text(encoding="utf-8"))
    elif local_path.is_file():
        data = json.loads(local_path.read_text(encoding="utf-8"))
    else:
        data = {"profiles": [{"name": "Lab HA Broker"}], "device_mappings": []}

    if not data.get("profiles"):
        data["profiles"] = [{"name": "Lab HA Broker"}]
    data["profiles"][0].update(
        {
            "host": host,
            "port": port,
            "client_id": data["profiles"][0].get("client_id", "RamMQTT"),
            "username": username,
            "password": password,
        }
    )
    local_path.parent.mkdir(parents=True, exist_ok=True)
    local_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {local_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="RamAI OS Keyring helper (Windows Credential Manager)",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("list", help="List known RamAI keyring entries")
    p.set_defaults(func=cmd_list)

    p = sub.add_parser("get", help="Get one entry")
    p.add_argument("key", choices=KEYS)
    p.add_argument("--show", action="store_true", help="Print password values")
    p.set_defaults(func=cmd_get)

    p = sub.add_parser("set", help="Set one entry")
    p.add_argument("key", choices=KEYS)
    p.add_argument(
        "value",
        nargs="?",
        default=None,
        help="Value (omit to be prompted; passwords are hidden)",
    )
    p.set_defaults(func=cmd_set)

    p = sub.add_parser("delete", help="Delete one entry")
    p.add_argument("key", choices=KEYS)
    p.set_defaults(func=cmd_delete)

    p = sub.add_parser(
        "import-local",
        help="Import from existing secrets.h / mqtt_local.json / local_profile.json",
    )
    p.set_defaults(func=cmd_import_local)

    p = sub.add_parser(
        "write-arduino",
        help="Write gitignored secrets.h files for all Arduino sketches",
    )
    p.set_defaults(func=cmd_write_arduino)

    p = sub.add_parser(
        "write-configs",
        help="Write gitignored Unreal mqtt_local.json and RamMQTT local_profile.json",
    )
    p.set_defaults(func=cmd_write_configs)

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
